version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"