version: '3.8'
services:
  db:
    build:
      context: ./db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  node-service:
    build:
      context: ./api
    restart: always
    environment:
      DB_HOST: ${DB_HOST}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}


    # ports:
    #  - "3000:3000"

    depends_on:
      - db

  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - node-service

volumes:
  db-data:
